<?php
require_once 'PHPUnit/Framework.php';

require_once '../osmosis.php';

/**
 * Test class for Osmosis.
 * Generated by PHPUnit on 2010-06-04 at 23:48:09.
 */
class OsmosisTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Osmosis
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new Osmosis;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    public function testLexerHeading()
    {
		$this->object->LoadFile('./text/heading.txt');
		$this->object->Lexer();
		$result = $this->object->GetIntermediateCode();
		$expected = array(Osmosis::HEADING_TOKEN, "Heading");
		$this->assertEquals($expected, $result);
	}

	public function testParserHeading()
    {
		$this->object->LoadFile('./text/heading.txt');
		$this->object->Lexer();
		$result = $this->object->Parser();
		$expected = "<h1>Heading</h1>\n";
		$this->assertEquals($expected, $result);
	}

	public function testLexerCode()
	{
		$this->object->LoadFile('./text/code.txt');
		$this->object->Lexer();
		$result = $this->object->GetIntermediateCode();
		$expected = array(Osmosis::CODE_START_TOKEN, "code","more code","more code", "", "even more code", Osmosis::CODE_END_TOKEN);
		$this->assertEquals($expected, $result);
	}

	public function testParserCode()
    {
		$this->object->LoadFile('./text/code.txt');
		$this->object->Lexer();
		$result = $this->object->Parser();
		$expected = "<pre>code\nmore code\nmore code\n\neven more code\n</pre>\n";
		$this->assertEquals($expected, $result);
	}

	public function testLexerPara()
	{
		$this->object->LoadFile('./text/para.txt');
		$this->object->Lexer();
		$result = $this->object->GetIntermediateCode();
		$expected = array(Osmosis::PARA_START_TOKEN, "some random text", Osmosis::PARA_END_TOKEN);
		$this->assertEquals($expected, $result);
	}

	public function testParserPara()
    {
		$this->object->LoadFile('./text/para.txt');
		$this->object->Lexer();
		$result = $this->object->Parser();
		$expected = "<p>some random text\n</p>\n";
		$this->assertEquals($expected, $result);
	}

	public function testLexerComplete()
	{
		$this->object->LoadFile('./text/complete.txt');
		$this->object->Lexer();
		$result = $this->object->GetIntermediateCode();
		$expected = array(Osmosis::HEADING_TOKEN, "Heading", Osmosis::PARA_START_TOKEN, "some random text", 'more text same paragraph', Osmosis::PARA_END_TOKEN, Osmosis::CODE_START_TOKEN, "code","more code","more code", "", "even more code", Osmosis::CODE_END_TOKEN);
		$this->assertEquals($expected, $result);
    }

	public function testParserComplete()
    {
		$this->object->LoadFile('./text/complete.txt');
		$this->object->Lexer();
		$result = $this->object->Parser();
		$expected = "<h1>Heading</h1>\n<p>some random text\nmore text same paragraph\n</p>\n<pre>code\nmore code\nmore code\n\neven more code\n</pre>\n";
		$this->assertEquals($expected, $result);
	}

	public function testParserMySqlNotes()
    {
		$this->object->LoadFile('./text/mysql-permissions');
		$this->object->Lexer();
		$result = $this->object->Parser();
		$expected = "<h1>MySQL Permissions Cheat Sheet</h1>\n<h2>Create a regular user</h2>\n<pre>GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER\nON database.* TO &#039;monty&#039;@&#039;localhost&#039;\nIDENTIFIED BY &#039;some_pass&#039;;\n\n</pre>\n<h2>Drop a user</h2>\n<pre>DROP USER &#039;monty&#039;@&#039;localhost&#039;;\n</pre>\n";

		$this->assertEquals($expected, $result);
	}
	public function testParserApache()
    {
		$this->object->LoadFile('./text/apache.txt');
		$this->object->Lexer();
		$result = $this->object->Parser();
		$expected = "<h1>The most basic apache virtual host</h1>\n<pre>&lt;VirtualHost *:80&gt;\n    ServerName localhost\n    DocumentRoot /var/www\n&lt;/VirutalHost&gt;\n\n</pre>\n<h2>Another apache directive</h2>\n<pre>&lt;Location /var/www&gt;\n    Options Indexes\n    Order allow,deny\n    Allow from All\n&lt;/Location&gt;\n</pre>\n";

		$this->assertEquals($expected, $result);
	}
}
